# Dockerfile.train
FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y gcc libgomp1 curl && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy training scripts
COPY main.py .
COPY src ./src

# Command to run training
CMD ["python", "main.py"]
