# Dockerfile.serve
FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y \
    libgomp1 curl && rm -rf /var/lib/apt/lists/*

# Copy only minimal requirements
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy app and prediction pipeline
COPY app.py .
COPY src/mlProject/pipeline/prediction.py ./src/mlProject/pipeline/prediction.py

# Copy templates and static
COPY templates ./templates
COPY static ./static

# Expose port for Flask
EXPOSE 8080

# Run Flask
CMD ["python", "app.py"]
